# --------------------------
# Build hosts list
# --------------------------
- name: Build host entries
  set_fact:
    host_entries:
      - "{{ magazine }}"
      - "api.{{ magazine }}"
      - "api.magsquare.com"

# --------------------------
# Add entries to /etc/hosts
# --------------------------
- name: Add domains to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
    state: present
  loop: "{{ host_entries }}"
