- set_fact:
  host_entries:
    - "{{ magazine }}"
    - "api.{{ magazine }}"

- name: Add hosts
  lineinfile:
  path: "{{ current_platform.hosts_file }}"
  line: "127.0.0.1 {{ item }}"
  state: present
  loop: "{{ host_entries }}"
